export const CINEMA_HOME_REQUEST = "CINEMA_COMPONET/CINEMA_HOME_REQEST";
export const CINEMA_HOME_SUCCESS = "CINEMA_COMPONET/CINEMA_HOME_SUCCESS";
export const CINEMA_HOME_FAILED = "CINEMA_COMPONET/CINEMA_HOME_FAILED";
export const CINEMA_SYSTEM_HOME_REQUEST =
  "CINEMA_COMPONET/CINEMA_SYSTEM_HOME_REQUEST";
export const CINEMA_SYSTEM_HOME_SUCCESS =
  "CINEMA_COMPONET/CINEMA_SYSTEM_HOME_SUCCESS";
export const CINEMA_SYSTEM_HOME_FAILED =
  "CINEMA_COMPONET/CINEMA_SYSTEM_HOME_FAILED";
