export const DASHBOARD_REQUEST = "DASHBOARD/DASHBOARD_REQEST";
export const DASHBOARD_SUCCESS = "DASHBOARD/DASHBOARD_SUCCESS";
export const DASHBOARD_FAILED = "DASHBOARD/DASHBOARD_FAILED";
export const DASHBOARD_FILM_REQUEST = "DASHBOARD_FILM/DASHBOARD_REQEST";
export const DASHBOARD_FILM_SUCCESS = "DASHBOARD_FILM/DASHBOARD_SUCCESS";
export const DASHBOARD_FILM_FAILED = "DASHBOARD_FILM/DASHBOARD_FAILED";
export const DASHBOARD_ADD_USER_REQUEST = "DASHBOARD_ADD_USER/DASHBOARD_REQEST";
export const DASHBOARD_ADD_USER_SUCCESS =
  "DASHBOARD_ADD_USER/DASHBOARD_SUCCESS";
export const DASHBOARD_ADD_USER_FAILED = "DASHBOARD_ADD_USER/DASHBOARD_FAILED";
