export const FILM_HOME_REQUEST = "FILM_COMPONET/FILM_HOME_REQEST";
export const FILM_HOME_SUCCESS = "FILM_COMPONET/FILM_HOME_SUCCESS";
export const FILM_HOME_FAILED = "FILM_COMPONET/FILM_HOME_FAILED";
export const FILM_HOME_MOVIE = "FILM_COMPONET/FILM_HOME_FETCH";
